# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0aec558489e990981ca642107b71fc6a4482dee5fe07b7d30ec6f36f108869e53e139eee6a5960a533c05e420e552bb3a9c412daf80aa781c21d2eaae41fdc20
  admin:
    email: 'admin@imap-guide.com'
    password: '12345678'
  google_maps:
    key: 'AIzaSyAT6stp68lqoea5a1R6EqwGd5s-mBW9s8w'

test:
  secret_key_base: 3873179db72875dcb6c5067ac58839e863fd6e0e9f7fb3d36a361c76b20ebf70f2d8c5de6e35ee17fe468efb80c04a6eb8e26270abdc9f348e3799abef964f41
  admin:
  email: 'admin-tester@imap-guide.com'
  password: '12345678'

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  admin:
    email: 'admin@imap-guide.com'
    password: '12345678'
  google_maps:
    key: 'AIzaSyAT6stp68lqoea5a1R6EqwGd5s-mBW9s8w'

